# The URL the site will be built for
base_url = "https://blog.dotone.top"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
#highlight_code = true

highlight_theme = "material-dark"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "even"

title="Lei's Blog"

default_language="zh"

generate_feed = true

taxonomies = [
    {name = "categories", feed  = true},
    {name = "tags", feed  = true},
]

[slugify]
paths="safe"

[markdown]
highlight_code = true

[extra]
even_title="Lei's Blog"
even_menu = [
    {url = "$BASE_URL", name = "Home"},
    {url = "$BASE_URL/categories", name = "Categories"},
    {url = "$BASE_URL/tags", name = "Tags"},
    {url = "$BASE_URL/about", name = "About"},
]
katex_enable = true
katex_auto_render = true

# Google Analytics
ga_id="UA-177611810-1"

base_url="https://blog.dotone.top"
