on:
  push:
    branches:
      - code
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/code'
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Build only"
        uses: shalzz/zola-deploy-action
        env:
          BUILD_DIR: .
          TOKEN: ${{ secrets.TOKEN }}
          BUILD_ONLY: true
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/code'
    steps:
      - name: "Checkout"
        uses: actions/checkout@master
      - name: "Build and deploy"
        uses: shalzz/zola-deploy-action
        env:
          PAGES_BRANCH: master
          BUILD_DIR: .
          TOKEN: ${{ secrets.TOKEN }}
